/**
 * Static sticker registry.
 *
 * Metro requires literal require() paths, so this file is GENERATED by
 * scripts/generate-stickers.js consumers — edit that script, not this file.
 */

export interface StickerAsset { id: string; source: number; }
export interface StickerPack { id: string; name: string; stickers: StickerAsset[]; }

export const STICKER_PACKS: StickerPack[] = [
  {
    id: 'emotions',
    name: 'ChipApp Emotions',
    stickers: [
      { id: 'grinning', source: require('../../assets/stickers/emotions/grinning.png') },
      { id: 'smiling', source: require('../../assets/stickers/emotions/smiling.png') },
      { id: 'in-love', source: require('../../assets/stickers/emotions/in-love.png') },
      { id: 'winking', source: require('../../assets/stickers/emotions/winking.png') },
      { id: 'surprised', source: require('../../assets/stickers/emotions/surprised.png') },
      { id: 'sad', source: require('../../assets/stickers/emotions/sad.png') },
      { id: 'neutral', source: require('../../assets/stickers/emotions/neutral.png') },
      { id: 'sleepy', source: require('../../assets/stickers/emotions/sleepy.png') },
      { id: 'cool', source: require('../../assets/stickers/emotions/cool.png') },
      { id: 'blush', source: require('../../assets/stickers/emotions/blush.png') },
    ],
  },
  {
    id: 'hands',
    name: 'ChipApp Hands',
    stickers: [
      { id: 'thumbs-up', source: require('../../assets/stickers/hands/thumbs-up.png') },
      { id: 'thumbs-down', source: require('../../assets/stickers/hands/thumbs-down.png') },
      { id: 'ok-hand', source: require('../../assets/stickers/hands/ok-hand.png') },
      { id: 'wave', source: require('../../assets/stickers/hands/wave.png') },
      { id: 'clap', source: require('../../assets/stickers/hands/clap.png') },
      { id: 'peace', source: require('../../assets/stickers/hands/peace.png') },
      { id: 'raised-hand', source: require('../../assets/stickers/hands/raised-hand.png') },
      { id: 'fist-bump', source: require('../../assets/stickers/hands/fist-bump.png') },
    ],
  },
  {
    id: 'objects',
    name: 'ChipApp Objects',
    stickers: [
      { id: 'heart', source: require('../../assets/stickers/objects/heart.png') },
      { id: 'star', source: require('../../assets/stickers/objects/star.png') },
      { id: 'fire', source: require('../../assets/stickers/objects/fire.png') },
      { id: 'party', source: require('../../assets/stickers/objects/party.png') },
      { id: 'coffee', source: require('../../assets/stickers/objects/coffee.png') },
      { id: 'gift', source: require('../../assets/stickers/objects/gift.png') },
      { id: 'rocket', source: require('../../assets/stickers/objects/rocket.png') },
      { id: 'cake', source: require('../../assets/stickers/objects/cake.png') },
      { id: 'thumbup-badge', source: require('../../assets/stickers/objects/thumbup-badge.png') },
      { id: 'check-badge', source: require('../../assets/stickers/objects/check-badge.png') },
    ],
  },
];

export const ALL_STICKERS = STICKER_PACKS.flatMap((p) => p.stickers);
